import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "Characteristics": "Characteristics",
          "Safe Zone": "Safe Zone",
          "Blood Type": "Blood Type",
          "Share": "Share",
          "Save": "Save",
          "Home": "Home",
          "Registration List": "Registration List",
          "Company": "Company",
          "Account": "Account",
          "Password": "Password",
          "Continue": "Continue",
          "ID": "ID",
          "Yes": "Yes",
          "No": "No",
          "Name": "Name",
          "Regidence": "Regidence",
          "safeZone": "safeZone",
          "Registration": "Registration",
          "Age": "Age",
          "Profile": "Profile",
          "Description": "Description",
          "Escorteres can now locate the": "Escorteres can now locate the",
          "patient": "patient",
          "close": "close",
          "Clairo": "Clairo",
          "Loading": "Loading",
          "Loading...": "Loading...",
          "Scan QR Code": "Scan QR Code",
          "Please scan the old man's QR code.":
              "Please scan the old man's QR code.",
          "Register the elderly to the registration list.":
              "Register the elderly to the registration list.",
          "Scan Successful!": "Scan Successful!",
          "The old man has been registered on the registration list.":
              "The old man has been registered on the registration list.",
          "Go to Home": "Go to Home",
          "Scan Failure!": "Scan Failure!",
          "Invalid qr code or network error.":
              "Invalid qr code or network error.",
          "Try again": "Try again",
          "Scan Failure!": "Scan Failure!",
          "Invalid qr code.": "Invalid qr code.",
          "Try again": "Try again",
          "no Permission": "no Permission",
          "Not Danger": "Not Danger",
          "If you know what he's wearing today, please write it":
              "If you know what he's wearing today, please write it",
          "Successful in calling": "Successful in calling",
          "Ask For Help": "Ask For Help",
          "Partner Benefit": "Partner Benefit",
          "Get a place to rest and coffee discounts for families with dementia!":
              "Get a place to rest and coffee discounts for families with dementia!",
          "Personal Information": "Personal Information",
          "Account Settings": "Account Settings",
          "Participate as an Company": "Participate as an Company",
          "Who are you?": "Who are you?",
          "Tell us about yourself. You can change it":
              "Tell us about yourself. You can change it",
          "later on the MyPage.": "later on the MyPage.",
          "Date of birth": "Date of birth",
          "Phone Number": "Phone Number",
          "Create Your Account": "Create Your Account",
          "Enter your E-mail address and password":
              "Enter your E-mail address and password",
          "E-mail Address": "E-mail Address",
          "Confirm Password": "Confirm Password",
          "Give Us More Detail About You!": "Give Us More Detail About You!",
          "The information is necessary to use our":
              "The information is necessary to use our",
          "service.": "service.",
          "Your Image": "Your Image",
          "Blood Type": "Blood Type",
          "Camera Shoot": "Camera Shoot",
          "Album": "Album",
          "Your Favorite Place": "Your Favorite Place",
          "Set up your safe zone": "Set up your safe zone",
          "Search the address or move the map":
              "Search the address or move the map",
          "Your account has been created": "Your account has been created",
          "Let\'s begin!": "Let\'s begin!",
          "Go to Home": "Go to Home",
          "Sign Up Successful!": "Sign Up Successful!",
          "QR code": "QR code",
          "Show Escorter and simply register with each other!":
              "Show Escorter and simply register with each other!",
          "Welcome To Escort!": "Welcome To Escort!",
          "Our new platform came to ease you accompanies the elderly with dementia.":
              "Our new platform came to ease you accompanies the elderly with dementia.",
          "Wherever You Are": "Wherever You Are",
          "Our app prevents the disappearance of elderly people with dementia.":
              "Our app prevents the disappearance of elderly people with dementia.",
          "Sign Up For Escort": "Sign Up For Escort",
          "You can also participate and help the elderly with dimentia.":
              "You can also participate and help the elderly with dimentia.",
          "Forgot password? Click here": "Forgot password? Click here",
          "Get Started": "Get Started",
          "I Already Have an Account": "I Already Have an Account",
          "Sign In": "Sign In",
          "Please enter Your ID and Password":
          "Please enter Your ID and Password",
          "Do you have Dementia?": "Do you have Dementia?",
          "This information is necessary to use our service.": "This information is necessary to use our service."
        },
        'ko': {
          "Characteristics": "특징",
          "Safe Zone": "안전 구역",
          "Blood Type": "혈액형",
          "Share": "공유",
          "Save": "저장",
          "Home": "홈",
          "Registration List": "노인 목록",
          "Company": "회사",
          "Account": "계정",
          "Password": "비밀번호",
          "Continue": "다음",
          "ID": "아이디",
          "Yes": "네",
          "No": "아니요",
          "Name": "이름",
          "Regidence": "거주지",
          "safeZone": "안전 구역",
          "Registration": "거주지",
          "Age": "나이",
          "Profile": "프로필",
          "Description": "설명",
          "Escorteres can now locate the": "에스코터는 이제",
          "patient": "환자",
          "close": "닫기",
          "Clairo": "클라리오",
          "Loading": "로딩",
          "Loading...": "로딩...",
          "Scan QR Code": "QR 코드 스캔",
          "Please scan the old man's QR code.": "노인의 QR 코드를 스캔해주세요.",
          "Register the elderly to the registration list.": "노인을 노인 목록에 등록하세요.",
          "Scan Successful!": "스캔 성공!",
          "The old man has been registered on the registration list.": "이미 등록된 노인입니다.",
          "Go to Home": "홈으로 이동",
          "Scan Failure!": "스캔 실패!",
          "Invalid qr code or network error.": "잘못된 QR 코드이거나 네트워크 오류가 발생하였습니다.",
          "Try again": "다시 시도",
          "Invalid qr code.": "잘못된 QR 코드 입니다.",
          "no Permission": "권한 없음",
          "Not Danger": "위험 없음",
          "If you know what he's wearing today, please write it": "오늘 입은 옷을 알고 있다면 적어주세요.",
          "Successful in calling": "호출 성공",
          "Ask For Help": "도움 요청",
          "Partner Benefit": "파트너 혜택",
          "Get a place to rest and coffee discounts for families with dementia!":
              "치매 가족을 위한 휴식 공간과 커피 할인 혜택을 받으세요!",
          "Personal Information": "개인 정보",
          "Account Settings": "계정 설정",
          "Participate as an Company": "기업으로 참여하기",
          "Who are you?": "당신은 누구인가요?",
          "Tell us about yourself. You can change it": "정보를 입력해주세요. 나중에",
          "later on the MyPage.": "마이페이지에서 변경할 수 있습니다.",
          "Date of birth": "생년월일",
          "Phone Number": "전화번호",
          "Create Your Account": "계정 만들기",
          "Enter your E-mail address and password": "이메일과 비밀번호를 입력해주세요",
          "E-mail Address": "이메일 주소",
          "Confirm Password": "비밀번호 확인",
          "Give Us More Detail About You!": "더 자세한 정보를 입력해주세요!",
          "The information is necessary to use our": "서비스를 이용하기 위해 필요한 정보입니다.",
          "service.": "서비스.",
          "Your Image": "이미지",
          "Camera Shoot": "사진 촬영",
          "Album": "앨범",
          "Your Favorite Place": "좋아하는 장소",
          "Set up your safe zone": "안전 구역을 설정해주세요",
          "Search the address or move the map": "주소를 검색하거나 지도를 움직여주세요",
          "Your account has been created": "계정이 생성되었습니다",
          "Let\'s begin!": "시작해볼까요?",
          "Go to Home": "홈으로 이동",
          "Sign Up Successful!": "회원가입 성공!",
          "QR code": "QR 코드",
          "Show Escorter and simply register with each other!": "Escorter에게 보여주고 간단하게 등록하세요!",
          "Welcome To Escort!": "Escort에 오신 것을 환영합니다!",
          "Our new platform came to ease you accompanies the elderly with dementia.":
              "치매 노인과 동행인의 편의를 도와드립니다.",
          "Wherever You Are": "어디서든",
          "Our app prevents the disappearance of elderly people with dementia.":
              "치매 노인의 실종을 예방합니다.",
          "Sign Up For Escort": "Escort 가입하기",
          "You can also participate and help the elderly with dimentia.": "주변에 있는 치매 노인을 도와줄 수 있습니다.",
          "Forgot password? Click here": "비밀번호를 잊으셨나요? 여기를 클릭하세요",
          "Get Started": "시작하기",
          "I Already Have an Account": "이미 계정이 있으신가요?",
          "Sign In": "로그인",
          "Please enter Your ID and Password":
              "아이디와 비밀번호를 입력해주세요",
          "Do you have Dementia?": "치매가 있으신가요?",
          "This information is necessary to use our service.": "서비스를 이용하기 위해 필요한 정보입니다.",
        },
      };
}
